on: [push]

name: Check and Format

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1.0.1
        with:
          command: check

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --check
